language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libxrandr-dev xorg-dev

script:
  - rustc --version
  - cargo --version
  - cargo build --verbose
  - cargo test --lib --verbose
  - cd examples && cargo check --verbose
