language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

matrix:
  allow_failures:
    - rust: nightly
    - os: osx

script:
  - rustc --version
  - cargo --version
  - cd luminance
  - cargo build --verbose
  - cd ../luminance-gl
  - cargo build --verbose
