[package]
name = "luminance"
version = "0.1.0"
authors = ["Dimitri Sabadie <dimitri.sabadie@gmail.com>"]
description = "Stateless and type-safe graphics framework"
readme = "README.md"
keywords = ["stateless", "type-safe", "graphics", "luminance"]
license = "BSD-3-Clause"
