[workspace]

members = [
  "01-hello-world",
  "02-render-state",
  "03-sliced-tess",
  "04-shader-uniforms",
  "05-attributeless",
  "06-texture",
  "07-offscreen",
  "08-shader-uniforms-adapt",
]

[patch.crates-io]
luminance = { path = ".." }
