[package]
name = "offscreen"
version = "0.1.0"
authors = ["Dimitri Sabadie <dimitri.sabadie@gmail.com>"]

[dependencies]
luminance = { version = "0.30", path = "../.." }
luminance-glfw = { version = "0.5", path = "../../../luminance-glfw" }
